# Generated by Django 5.0.7 on 2024-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfrs_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat'), ('rice', 'Rice')], max_length=20)),
                ('soil_type', models.CharField(max_length=50)),
                ('nitrogen_level', models.FloatField()),
                ('phosphorus_level', models.FloatField()),
                ('potassium_level', models.FloatField()),
                ('recommended_nitrogen', models.FloatField()),
                ('recommended_phosphorus', models.FloatField()),
                ('recommended_potassium', models.FloatField()),
            ],
        ),
    ]
